name: Java CI with Gradle and Test Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [build, test] # Define tasks to avoid duplicating jobs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Gradle ${{ matrix.task }}
        env:
          GOIT_DB2_URL: ${{ secrets.GOIT_DB2_URL }}
          GOIT_DB_USER: ${{ secrets.GOIT_DB_USER }}
          GOIT_DB_PASS: ${{ secrets.GOIT_DB_PASS }}
          SECRET: ${{ secrets.SECRET }}
          LOG_LEVEL: debug
        run: ./gradlew ${{ matrix.task }}

      - name: Upload Test Reports
        if: matrix.task == 'test' && always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/test-results/test/

      - name: Display Test Metrics
        if: matrix.task == 'test'
        run: |
          echo "Parsing test results..."
          TOTAL_TESTS=$(grep '<testsuite ' build/test-results/test/*.xml | grep -o 'tests="[0-9]*"' | awk -F'"' '{sum += $2} END {print sum}')
          FAILED_TESTS=$(grep '<testsuite ' build/test-results/test/*.xml | grep -o 'failures="[0-9]*"' | awk -F'"' '{sum += $2} END {print sum}')
          echo "Total Tests: $TOTAL_TESTS"
          echo "Failed Tests: $FAILED_TESTS"