name: Java CI with Gradle and Test Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ build, test ] # Define tasks to avoid duplicating jobs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Gradle ${{ matrix.task }}
        env:
          GOIT_DB2_URL: ${{ secrets.GOIT_DB2_URL }}
          GOIT_DB_USER: ${{ secrets.GOIT_DB_USER }}
          GOIT_DB_PASS: ${{ secrets.GOIT_DB_PASS }}
          SECRET: ${{ secrets.SECRET }}
          LOG_LEVEL: debug
        run: ./gradlew ${{ matrix.task }}

      - name: Publish JUnit Test Results
        if: matrix.task == 'test' && success() || failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'